Repository kiwiproject/champagne-service, pull requests merged in 2023-09, with the labels that each got.

#339 Add endpoint to retrieve build stats
  service/src/main/java/org/kiwiproject/champagne/App.java
  service/src/main/java/org/kiwiproject/champagne/dao/BuildDao.java
  service/src/main/java/org/kiwiproject/champagne/resource/MetricsResource.java
  service/src/test/java/org/kiwiproject/champagne/dao/BuildDaoTest.java
  service/src/test/java/org/kiwiproject/champagne/resource/MetricsResourceTest.java
  ui/src/stores/stats.js
Labels: enhancement

#348 Add User pages
  service/src/main/java/org/kiwiproject/champagne/App.java
  service/src/main/java/org/kiwiproject/champagne/dao/UserDao.java
  service/src/main/java/org/kiwiproject/champagne/dao/mappers/UserInSystemMapper.java
  service/src/main/java/org/kiwiproject/champagne/model/User.java
  service/src/main/java/org/kiwiproject/champagne/model/UserInSystem.java
  service/src/main/java/org/kiwiproject/champagne/resource/UserResource.java
  service/src/test/java/org/kiwiproject/champagne/dao/UserDaoTest.java
  service/src/test/java/org/kiwiproject/champagne/resource/UserResourceTest.java
  service/src/test/java/org/kiwiproject/champagne/resource/apps/TestUserApp.java
  ui/src/components/Dropdowns/TableActionsDropdown.vue
  ui/src/components/SideBar/SideBar.vue
  ui/src/router/index.js
  ui/src/views/ChampagneAdmin/UsersView.vue
  ui/src/views/SystemAdmin/SystemUsersView.vue
Labels: enhancement

#350 Add Audit viewing pages
  service/src/main/java/org/kiwiproject/champagne/dao/AuditRecordDao.java
  service/src/main/java/org/kiwiproject/champagne/resource/AuditRecordResource.java
  service/src/test/java/org/kiwiproject/champagne/dao/AuditRecordDaoTest.java
  service/src/test/java/org/kiwiproject/champagne/resource/AuditRecordResourceTest.java
  ui/src/components/Audits/AuditViewer.vue
  ui/src/components/SideBar/SideBar.vue
  ui/src/router/index.js
  ui/src/views/ChampagneAdmin/AuditsView.vue
  ui/src/views/SystemAdmin/SystemAuditsView.vue
Labels: enhancement

#351 Add System management page
  service/src/main/java/org/kiwiproject/champagne/App.java
  service/src/main/java/org/kiwiproject/champagne/dao/DeployableSystemDao.java
  service/src/main/java/org/kiwiproject/champagne/dao/DeploymentEnvironmentDao.java
  service/src/main/java/org/kiwiproject/champagne/dao/mappers/SystemUserMapper.java
  service/src/main/java/org/kiwiproject/champagne/model/DeployableSystem.java
  service/src/main/java/org/kiwiproject/champagne/resource/DeployableSystemResource.java
  service/src/test/java/org/kiwiproject/champagne/dao/DeploymentEnvironmentDaoTest.java
  service/src/test/java/org/kiwiproject/champagne/resource/DeployableSystemResourceTest.java
  ui/src/components/SideBar/SideBar.vue
  ui/src/router/index.js
  ui/src/views/ChampagneAdmin/SystemsView.vue
Labels: enhancement

#353 Fix build to only run sonar on specific versions of node and java
  .github/workflows/build.yml
Labels: refactoring

#375 Run build on zulu distribution of JDKs 17 and 21
  .github/workflows/build.yml
Labels: infrastructure
